### ISSUE TITLE
something I can't understand

### ISSUE THREAD

**Issue by Luoxd1996** [fidler-lab/polyrnn-pp-pytorch#1]
1.this command "python Scripts/prediction/generate_annotation.py --exp <path_to_corresponding_experiment> --reload <path_to_checkpoint> --output_dir <path_to_store_predictions>" I can't understand "<path_to_corresponding_experiment> ","<path_to_checkpoint>","<path_to_store_predictions> " refer  to， respectively.
2.I have tested this command "python Scripts/data/change_paths.py --city_dir <path_to_downloaded_leftImg8bit_folder> --json_dir <path_to_downloaded_annotation_file> --output_dir <output_dir>" and finded the "output_dir" should be replaced by "out_dir".
3.similar with problem 2，"python Scripts/train/train_ce.py --exp Experiments/mle.json --reload <optional_if_resuming_training>" in this command can't work ,but if use "resume" replace "reload" i can worked well.

**Comment by amlankar** [comment]
Thanks for pointing out the 
https://github.com/fidler-lab/polyrnn-pp-pytorch/commit/6a90469a788ea5dd1c03d2e179ef3c058a5f32a7 fixes this.

To answer your first question, if you are testing the RL checkpoint, then the experiment needs to be Experiments/rl.json. Basically, the experiment json file dictates how the model will be made and how the forward/backward passes will happen. Hope this helps.

Closing because a fix commit has been pushed. Feel free to re-open if you have more questions!
