### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by haofengac** [fidler-lab/polyrnn-pp-pytorch#12]
Hello, thanks for releasing the training script! I've got some suggestions on the code:
1. It would be great if paths in the processed cityscapes.tar.gz and the experiment jsons are not absolute but relative with symbolic links.
2. Python3 might be more convenient for most developers.

Again, thanks for releasing the code!

Useful resources:
1. https://docs.python.org/2/library/2to3.html
2. https://stackoverflow.com/questions/11392478/how-to-replace-a-string-in-multiple-files-in-linux-command-line

**Comment by arieling** [comment]
Hi, Thank you for your suggestions! 
1. Yes it will be nice to have relative path with symbolic links.
2. For now we would like to stay in Python2 since our checkpoints are dumps by pytorch compiled in Python2

**Comment by amlankar** [comment]
Hi @xanderchf,

We use absolute paths since our code and models (large files) live on separate file systems -- the code is mounted onto personal machines, while models are not. This is why we do not keep symlinks to the other filesystem. It's very easy to add symlinks and convert to relative paths since all code is run from the root of the project.

I agree about python3, and we will do this soon.

Thanks for the suggestions!
